"""add priority and notes fields

Revision ID: 358a8d211433
Revises: None
Create Date: 2016-06-11 16:12:42.456774

"""

# revision identifiers, used by Alembic.
revision = '358a8d211433'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pos', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('pos', sa.Column('priority', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pos', 'priority')
    op.drop_column('pos', 'notes')
    ### end Alembic commands ###
