"""increase shipip via name length

Revision ID: 4fa408715e8a
Revises: 358a8d211433
Create Date: 2016-07-03 11:19:07.963899

"""

# revision identifiers, used by Alembic.
revision = '4fa408715e8a'
down_revision = '358a8d211433'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temp')
    ### end Alembic commands ###
