"""add avatar_hash h field.

Revision ID: d6211be97a78
Revises: 360c7c7dfc93
Create Date: 2016-07-13 08:03:25.366134

"""

# revision identifiers, used by Alembic.
revision = 'd6211be97a78'
down_revision = '360c7c7dfc93'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
